### ISSUE TITLE
api_request to the proxy failed with status code 599, retrying...

### ISSUE THREAD

**Issue by akhalidy-IDM** [BlueCog/-zero-to-jupyterhub-k8s#1]
Hi there, thank you for posting these online. I am trying to deploy JupyterHub on openshift and the hub pod keeps showing 

[W 2022-02-02 22:33:47.015 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[W 2022-02-02 22:33:50.051 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[W 2022-02-02 22:33:53.388 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[W 2022-02-02 22:33:56.796 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[W 2022-02-02 22:34:00.631 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[W 2022-02-02 22:34:05.679 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[W 2022-02-02 22:34:09.450 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[W 2022-02-02 22:34:16.287 JupyterHub proxy:851] api_request to the proxy failed with status code 599, retrying...
[E 2022-02-02 22:34:16.288 JupyterHub app:2973]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2971, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2746, in start
        await self.proxy.get_all_routes()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 898, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 862, in api_request
        result = await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 184, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Repeated api_request to proxy path "" failed.

I would really appreciate any help to get a vanilla instance deployed on OpenShift.

**Comment by BlueCog** [comment]
hi @akhalidy-IDM 

Sorry for the late reply, it seems that i didn't receive an email alert. 

Not sure if your issue is still active but at first look this looks like a communication issue between pods.  Are there any network policies in place?

**Comment by BlueCog** [comment]
I've added default policies
