### ISSUE TITLE
Thanks - You are the best

### ISSUE THREAD

**Issue by ichtestemalwieder** [BlueCog/-zero-to-jupyterhub-k8s#2]
Hi, 

I can not express how thankfull I am for your great work. Your Repo helped me to get Jupyter Running on my Test OpenShift Cluster (for learning). Without your work/repo I would never have been able to get this running. 

Thanks so much for marking this world a better place and beeing so kind to donate you great work to the benefit of all. God bless you, Thanks again a million times, I wish you all the best! Thanks!

(Sorry for posting this as issue, I have not found a way to contact you other wise).

**Comment by BlueCog** [comment]
Thank you for your message @ichtestemalwieder  You are very welcome!
